- hosts: labservers
  become: yes
  tasks:
  - name: Remove httpd package
    yum:
      name: http
      state: absent 
  
  - name: Remove firewalld package
    yum:
      name: firewalld
      state: absent
